spring.application.name=docurel


spring.datasource.url=jdbc:postgresql://localhost:5432/docurel
spring.datasource.username=postgres
spring.datasource.password=YOUR_PASSWORD

spring.jpa.hibernate.ddl-auto=update
